global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 0.1
   publish_frequency: 0.1
   width: 90
   height: 90
   resolution: 0.01
   static_map: true
   rolling_window: false
